dima_auto_test:
    resource: "@DimaAutoTestBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix: /site

contact:
    path: /{_locale}/contact
    defaults: { _controller: AppBundle:Hello:contact }
    requirements:
        _locale: '%app.locales%'
